import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pictura AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <main className="flex flex-col min-h-screen">
          <Header />
          <div className="flex-2">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
